push.app-name=pushk-0.0.1
push.pool-send-push-size=1001
push.queue-update-status-size=100001
push.queue-send-push-size=100001
#push.db_url=jdbc:postgresql://fenomy.cc:5432/fenomy
push.db-url=jdbc:pgsql://fenomy.cc:5432/fenomy
push.db-user=push_bot
push.db-password=push_bot
#push.db_driver=org.postgresql.Driver
push.db_driver=com.impossibl.postgres.jdbc.PGDriver
spring.datasource.url=jdbc:pgsql://fenomy.cc:5432/fenomy
spring.datasource.driver-class-name=com.impossibl.postgres.jdbc.PGDriver
#spring.datasource.url=jdbc:postgresql://fenomy.cc:5432/fenomy
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.com.zaxxer.hikari=debug
logging.level.com.anksystems=debug
logging.level.com.anksystems.fenomy_pushk.FenomyPushkApplication=debug
logging.level.com.anksystems.fenomy_pushk.FenomyPushkApplicationKt=debug
logging.file.name=build/tmp/${push.app-name}.log

