push.send_workers=13
push.pg_workers=14
push.db_url=jdbc:postgresql://fenomy.cc:5432/fenomy
push.db_user=kernel
push.db_password=kernel
push.db_driver=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://fenomy.cc:5432/fenomy


